import type { Locale } from './locales';
import { LOCALE_NAMES, SITE_LOCALES } from './locales';
// ! `import type`, never a value import — `replies.ts` pulls in roll-parser, and
// ! `render.ts` is in the browser bundle. `verbatimModuleSyntax` erases this line;
// ! dropping the `type` keyword would ship the whole parser to every visitor.
import type { ResolvedExample, ResolvedManual } from './replies';

const BOT_HANDLE = '@rollrobot';
const TELEGRAM_URL = 'tg://resolve?domain=rollrobot';
const PLAYGROUND_URL = 'https://roll-parser.edloidas.io/';
const REFERENCE_URL = 'https://roll-parser.edloidas.io/reference';
const SOURCE_URL = 'https://github.com/edloidas/rollrobot';

/**
 * Escapes text destined for element content or a double-quoted attribute.
 *
 * Deliberately not shared with `src/format.ts`'s escaper, and merging the two
 * would be a regression: `format.ts` value-imports `roll-parser`, so reaching
 * for it here would ship the whole dice parser to every visitor — exactly what
 * the bundle ceiling in `check-site.ts` exists to catch. The two also differ on
 * purpose: this one escapes `"` for attribute contexts, the bot's strips
 * bidi-control characters instead.
 */
export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Wraps content that must read left-to-right whatever direction the page runs.
 *
 * Dice notation, the bot handle and generated replies are never translated, and
 * each one opens or closes on a bidi-neutral character — `/`, `@`, a bracket, an
 * operator. Inside `/fa/`'s RTL paragraph those neutrals take the paragraph's
 * direction: `/full 4d6kh3` renders as `full 4d6kh3/`, `[6↑, 5, 3, 1↓]` as
 * `]6↑, 5, 3, 1↓[`, `(1d6+2)*3` as `3*(1d6+2)`. `dir="ltr"` pins the whole run.
 *
 * Inert on the seven LTR pages. It is a helper rather than five literals so a
 * sixth LTR element added later cannot quietly ship without it.
 */
function ltr(tag: string, html: string, className?: string): string {
  const classAttr = className === undefined ? '' : ` class="${className}"`;

  return `<${tag}${classAttr} dir="ltr">${html}</${tag}>`;
}

/**
 * Inline code and bold, in one pass so the two cannot overlap.
 *
 * Alternation, not two `replace` calls: matched left to right, a `**` inside a
 * code span is consumed by the code branch before the bold branch can see it.
 * Running the two separately would let either mangle the other's contents.
 *
 * A bold span is plain text by construction — it may hold neither `*` nor a
 * backtick — so bold and code never nest in either direction.
 */
const MARKUP = /`([^`]+)`|\*\*([^*`]+)\*\*/g;

/**
 * Escapes prose, rendering its `` `…` `` spans as inline code and `**…**` bold.
 *
 * Notation, commands and the bot handle read as literals in the middle of a
 * sentence, and marking them in the content is what keeps that decision with the
 * person writing the sentence. Detecting them instead would have to guess: `д20`
 * and `к6` are notation the bot accepts, which makes every Cyrillic paragraph a
 * minefield, and a bare `d100` is a word in some sentences and a die in others.
 *
 * Escaping runs first, so a span can never introduce markup — by the time the
 * spans are found, anything inside them is already inert text. Neither backticks
 * nor asterisks are escaped, so both survive that pass. An unpaired delimiter
 * stays a literal character.
 */
export function prose(text: string): string {
  return escapeHtml(text).replace(MARKUP, (_match, code?: string, bold?: string) =>
    code === undefined ? `<strong>${bold}</strong>` : ltr('code', code),
  );
}

/**
 * `lang`/`dir` for a block that took English because the locale supplies none.
 *
 * `dir` is inert on the seven LTR pages and load-bearing on `/fa/`, where
 * without it English prose lays out right-aligned with its sentence-final
 * punctuation thrown to the visual start of the line.
 */
function fallbackAttrs(fellBack: boolean): string {
  return fellBack ? ' lang="en" dir="ltr"' : '';
}

function renderReply(example: ResolvedExample): string {
  // ! `replyHtml` is generated by the bot's own handlers, which escape their
  // ! inputs. Do not escape it again here — that would print the markup as text.
  return (
    `<div class="example">` +
    ltr('div', `<code>${escapeHtml(example.typed)}</code>`, 'example-in') +
    ltr('div', example.replyHtml, 'reply') +
    `</div>`
  );
}

/**
 * The two roll-parser links, as cards rather than a line of prose.
 *
 * They sit above the tables because they are where a reader goes when the tables
 * stop being enough, and a link under six of them is a link nobody scrolls to.
 */
function linkCards(links: { href: string; label: string }[]): string {
  const cards = links
    .map(
      (link) =>
        `<a class="link-card" href="${link.href}">` +
        `<span>${escapeHtml(link.label)}</span>` +
        `<span class="link-arrow" aria-hidden="true">↗</span></a>`,
    )
    .join('');

  return `<div class="link-cards">${cards}</div>`;
}

/** Fiddly points under a summary. Returns nothing at all when there are none. */
function notes(lines: string[] | undefined): string {
  if (lines == null || lines.length === 0) return '';

  return `<ul class="notes">${lines.map((line) => `<li>${prose(line)}</li>`).join('')}</ul>`;
}

export function renderHero(manual: ResolvedManual, _locale: Locale): string {
  return (
    `<header class="hero"${fallbackAttrs(manual.fallback.hero)}>` +
    `<div class="card">` +
    `<svg class="card-pattern" aria-hidden="true">` +
    `<rect width="100%" height="100%" fill="url(#dice-pattern)"/></svg>` +
    `<div class="card-inner">` +
    `<img class="avatar" src="/favicon.svg" width="54" height="54" alt="" />` +
    `<h1 class="name">Roll Robot</h1>` +
    ltr('p', BOT_HANDLE, 'handle') +
    `<p class="tagline">${escapeHtml(manual.hero.tagline)}</p>` +
    `<a class="cta" href="${TELEGRAM_URL}">${escapeHtml(manual.hero.cta)}</a>` +
    `</div></div></header>`
  );
}

export function renderTabs(active: Locale): string {
  const tabs = SITE_LOCALES.map((locale) => {
    const current = locale === active ? ' aria-current="page"' : '';
    return (
      `<a class="tab" href="/${locale}/" lang="${locale}" data-locale="${locale}"${current}>` +
      `<span class="tab-long">${escapeHtml(LOCALE_NAMES[locale])}</span>` +
      // The narrow-screen label below 720px. A locale code is a fixed ASCII
      // literal, never translated text, so it needs no escaping.
      `<span class="tab-short">${locale.toUpperCase()}</span>` +
      `</a>`
    );
  }).join('');

  // Three elements, not two: the full-bleed bar paints the sticky background and
  // rule, the middle element scrolls when the tabs overflow, and the track
  // centres them. See the `.tabs` rules in style.css.
  return (
    `<nav class="tabs" aria-label="Language"><div class="tabs-scroll">` +
    `<div class="tabs-track">${tabs}</div></div></nav>`
  );
}

function section(id: string, heading: string, body: string, fellBack: boolean): string {
  return (
    `<section id="${id}"${fallbackAttrs(fellBack)}>` +
    `<h2>${escapeHtml(heading)}</h2>${body}</section>`
  );
}

function paragraphs(lines: string[]): string {
  return lines.map((line) => `<p>${prose(line)}</p>`).join('');
}

export function renderManual(manual: ResolvedManual, _locale: Locale): string {
  const commands = manual.commands.items
    .map((item) => {
      const shortcut = item.shortcut
        ? ` <span class="shortcut">/${escapeHtml(item.shortcut)}</span>`
        : '';
      // ! The whole heading, not just the <code>: the shortcut opens on a neutral
      // ! `/` too, and the h3 is a flex row whose two children would otherwise
      // ! sit in reverse order on /fa/.
      return (
        `<article class="command">` +
        ltr('h3', `<code>/${escapeHtml(item.command)}</code>${shortcut}`) +
        `<p>${prose(item.summary)}</p>` +
        notes(item.notes) +
        (item.example == null ? '' : renderReply(item.example)) +
        `</article>`
      );
    })
    .join('');

  const features = manual.specialFeatures.items
    .map(
      (item) =>
        `<article class="feature"><h3>${escapeHtml(item.title)}</h3>` +
        `<p>${prose(item.description)}</p>` +
        (item.important == null ? '' : `<p class="callout">${prose(item.important)}</p>`) +
        (item.example == null ? '' : renderReply(item.example)) +
        `</article>`,
    )
    .join('');

  const notation = manual.notation.groups
    .map((group) => {
      // ! Only the notation cell — the description beside it is prose and
      // ! follows the page direction.
      const rows = group.rows
        .map(
          (row) =>
            `<tr><td>${ltr('code', escapeHtml(row.notation))}</td>` +
            `<td>${prose(row.description)}</td></tr>`,
        )
        .join('');
      return (
        `<h3>${escapeHtml(group.heading)}</h3>` +
        `<div class="table-scroll"><table><tbody>${rows}</tbody></table></div>`
      );
    })
    .join('');

  const systems = manual.systems.items
    .map(
      (item) =>
        `<article class="recipe"><h3>${escapeHtml(item.system)}</h3>` +
        `<p>${prose(item.description)}</p>${renderReply(item.example)}</article>`,
    )
    .join('');

  const faq = manual.faq.items
    .map(
      (item) =>
        `<details><summary>${prose(item.question)}</summary>` +
        `<p>${prose(item.answer)}</p></details>`,
    )
    .join('');

  const fallback = manual.fallback;

  return (
    `<main class="manual">` +
    section(
      'getting-started',
      manual.gettingStarted.heading,
      paragraphs(manual.gettingStarted.body),
      fallback.gettingStarted,
    ) +
    section(
      'commands',
      manual.commands.heading,
      `<p>${prose(manual.commands.intro)}</p>${commands}`,
      fallback.commands,
    ) +
    section(
      'special-features',
      manual.specialFeatures.heading,
      `<p>${prose(manual.specialFeatures.intro)}</p>${features}`,
      fallback.specialFeatures,
    ) +
    section('inline', manual.inline.heading, paragraphs(manual.inline.body), fallback.inline) +
    section(
      'notation',
      manual.notation.heading,
      `<p>${prose(manual.notation.intro)}</p>` +
        linkCards([
          { href: PLAYGROUND_URL, label: manual.notation.links.playground },
          { href: REFERENCE_URL, label: manual.notation.links.reference },
        ]) +
        notation,
      fallback.notation,
    ) +
    section(
      'systems',
      manual.systems.heading,
      `<p>${prose(manual.systems.intro)}</p>${systems}`,
      fallback.systems,
    ) +
    section('limits', manual.limits.heading, paragraphs(manual.limits.body), fallback.limits) +
    section('faq', manual.faq.heading, faq, fallback.faq) +
    `<footer class="footer"${fallbackAttrs(fallback.footer)}>` +
    `<a href="${PLAYGROUND_URL}">${escapeHtml(manual.footer.playground)}</a>` +
    `<a href="${REFERENCE_URL}">${escapeHtml(manual.footer.reference)}</a>` +
    `<a href="${SOURCE_URL}">${escapeHtml(manual.footer.source)}</a>` +
    `</footer></main>`
  );
}
